from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
M109_PACKAGE_ID = "next90-m109-media-factory-build-explain-bundles"


class MaterializeMediaReleaseProofTests(unittest.TestCase):
    def assert_single_package_entry(self, packages: list[dict], package_id: str) -> dict:
        matches = [package for package in packages if package["package_id"] == package_id]
        self.assertEqual(1, len(matches), f"expected exactly one {package_id} successor package entry")
        return matches[0]

    def test_materializer_rejects_duplicate_successor_package_ids(self):
        script = (ROOT / "scripts/ai/materialize_media_release_proof.py").read_text(encoding="utf-8")

        for token in (
            "def require_unique_successor_package_ids(",
            "must contain exactly one successor package entry per package id",
            "require_unique_successor_package_ids(",
            "media_release_proof[\"successor_packages\"]",
            "artifact_publication_certification[\"successor_packages\"]",
        ):
            self.assertIn(token, script)

    def test_generated_receipts_pin_successor_package_closure(self):
        with tempfile.TemporaryDirectory() as tmp:
            subprocess.run(
                [
                    sys.executable,
                    "scripts/ai/materialize_media_release_proof.py",
                    "--out-dir",
                    tmp,
                    "--status",
                    "passed",
                ],
                cwd=ROOT,
                check=True,
                stdout=subprocess.DEVNULL,
            )

            release = json.loads((Path(tmp) / "MEDIA_LOCAL_RELEASE_PROOF.generated.json").read_text(encoding="utf-8"))
            certification = json.loads(
                (Path(tmp) / "ARTIFACT_PUBLICATION_CERTIFICATION.generated.json").read_text(encoding="utf-8")
            )

        self.assertEqual(
            len(release["successor_packages"]),
            len({package["package_id"] for package in release["successor_packages"]}),
            "release proof should contain exactly one successor package entry per package id",
        )
        self.assertEqual(
            len(certification["successor_packages"]),
            len({package["package_id"] for package in certification["successor_packages"]}),
            "artifact publication certification should contain exactly one successor package entry per package id",
        )

        expected_packages = {
            "next90-m108-media-factory-campaign-briefing-renders": {
                "frontier_id": 4459920059,
                "milestone_id": 108,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "ef3f006",
                "proof_floor_summary": "Pin M108 campaign briefing bundle closure with locale-bundled caption and preview siblings, bounded fallback locales, and length-prefixed receipt hashing",
                "owned_surfaces": [
                    "campaign_briefing_bundle_rendering",
                    "campaign_artifact_receipts",
                ],
                "artifact_roles": [
                    "CampaignColdOpen",
                    "CampaignMissionBriefing",
                    "CampaignCaption",
                    "CampaignPreview",
                ],
                "receipt_rows": [
                    "LocaleReceipts",
                    "LocaleBundleReceipts",
                    "CampaignBriefingLocaleBundleReceipt",
                    "ArtifactReceipts",
                    "CampaignBriefingLocaleReceipt",
                    "CampaignBriefingArtifactReceipt",
                    "CampaignBriefingFallbackSiblingReceipt",
                    "ColdOpenCaptionReceiptId",
                    "MissionBriefingCaptionReceiptId",
                    "ColdOpenPreviewReceiptId",
                    "MissionBriefingPreviewReceiptId",
                    "RequestedLocaleBundleReceiptId",
                    "FallbackLocales",
                    "FallbackLocaleBundleReceiptIds",
                    "ColdOpenReceiptIds",
                    "MissionBriefingReceiptIds",
                    "CaptionReceiptIds",
                    "PreviewReceiptIds",
                    "FallbackSiblingReceipts",
                    "JobIds",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/CampaignBriefingBundleService.cs",
                    "tests/test_m108_campaign_briefing_proof.py",
                    "docs/NEXT90_M108_CAMPAIGN_BRIEFING_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                ],
                "extra_key": "campaign_briefing_guards",
                "extra_value": [
                    "campaign briefing bundles require a requested-locale ColdOpen entry before rendering",
                    "campaign briefing bundles require a requested-locale MissionBriefing entry before rendering",
                    "campaign briefing bundles render media, caption, and preview siblings per locale entry",
                    "campaign briefing bundles keep the requested locale as the primary sibling and require every other locale to be a fallback sibling",
                    "campaign briefing bundles require locale-matched cold-open and mission briefing siblings for every requested and fallback locale bundle",
                    "campaign briefing bundles allow at most two fallback locales",
                    "campaign briefing receipts preserve asset urls, locale receipt ids, locale bundle receipt ids, and per-entry job ids",
                    "campaign briefing bundle receipts also preserve first-class requested-locale and fallback bundle summary fields",
                    "campaign briefing locale bundle and fallback sibling receipts preserve slot-aware caption and preview sibling ids",
                    "campaign briefing artifact receipts preserve approval state, retention state, and storage class alongside asset urls",
                    "campaign briefing dedupe keys include requested locale, slot, entry locale, fallback posture, category, output format, and caller dedupe",
                    "campaign briefing receipt hashes use length-prefixed locale, artifact-kind, and output-format segments so delimiter-heavy locale variants cannot collapse onto one receipt id",
                    "campaign briefing normalized locale-bundle ordering keeps locale receipts, locale bundle receipts, fallback sibling receipts, and summary job ids stable when callers reorder the same bundle entries",
                    "campaign briefing package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                ],
            },
            "next90-m107-media-factory-recipe-execution": {
                "frontier_id": 1746209281,
                "milestone_id": 107,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "398f756",
                "proof_floor_summary": "Pin M107 structured recipe receipt hardening with asset urls, stable replay ordering, and length-prefixed ref hashing",
                "owned_surfaces": [
                    "structured_media_recipe_execution",
                    "artifact_factory:receipts",
                ],
                "artifact_roles": [
                    "StructuredRecipeVideo",
                    "StructuredRecipeAudio",
                    "StructuredRecipePreviewCard",
                    "StructuredRecipePacketBundle",
                ],
                "receipt_rows": [
                    "PublicationRefReceipts",
                    "PublicationReadyRefs",
                    "StructuredMediaRecipePublicationReadyRef",
                    "JobIds",
                    "AssetUrl",
                    "CaptionRefReceipts",
                    "PreviewRefReceipts",
                    "RoleReceiptGroups",
                    "StructuredMediaRecipeRoleReceiptGroup",
                    "StructuredMediaRecipeRefArtifactReceipt",
                    "ArtifactReceipts",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/StructuredMediaRecipeExecutionService.cs",
                    "tests/test_m107_successor_closure_authority.py",
                    "docs/NEXT90_M107_MEDIA_RECIPE_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                ],
                "extra_key": "publication_ready_ref_guards",
                "extra_value": [
                    "recipe execution waits for completed media jobs before emitting publication-ready receipt refs",
                    "publication-ready refs preserve per-artifact ref, receipt id, job id, job state, output format, caption refs, preview refs, asset id, cache ttl, approval state, retention state, and storage class",
                    "artifact, publication-ready, publication-ref, caption-ref, and preview-ref receipt rows preserve direct asset urls so publication shelves do not need a follow-up asset lookup",
                    "bundle receipts expose aggregate JobIds matching every video, audio, preview-card, and packet-bundle artifact job",
                    "publication ref receipt rows preserve receipt id, job id, job state, output format, caption refs, preview refs, asset id, cache ttl, approval state, retention state, and storage class",
                    "role receipt groups preserve each video, audio, preview-card, and packet-bundle sibling's receipt ids, job ids, publication refs, caption refs, preview refs, lifecycle truth, and artifact rows",
                    "caption ref receipt rows group shared refs while preserving per-artifact publication, job, and lifecycle detail",
                    "caption ref receipt rows expose aggregate job ids and publication refs so shared caption evidence stays first-class without traversing nested artifact rows",
                    "preview ref receipt rows group shared refs while preserving packet-bundle publication, job, and lifecycle detail",
                    "preview ref receipt rows expose aggregate job ids and publication refs so shared preview evidence stays first-class without traversing nested artifact rows",
                    "grouped caption-ref and preview-ref artifact rows preserve per-artifact caption refs and preview refs so downstream shelves do not need to join back to the raw artifact receipt list",
                    "packet-bundle siblings require at least one preview ref before recipe execution",
                    "publication refs are unique per recipe bundle so publication-ready receipt rows remain unambiguous",
                    "role, caption, and preview receipt groups sort their receipt ids and refs explicitly so replayed bundles keep stable publication evidence ordering",
                    "job dedupe includes artifact category, output format, and publication ref so colliding caller dedupe keys cannot collapse different recipe outputs",
                    "job dedupe uses length-prefixed hashing so delimiter-heavy category, output format, publication ref, and caller dedupe values cannot collapse different recipe outputs",
                    "receipt hashes include caption and preview refs so publication-ready refs remain tied to their emitted caption and preview surfaces",
                    "receipt hashes use length-prefixed caption and preview ref segments so delimiter-heavy refs cannot collapse distinct publication-ready outputs onto one receipt id",
                ],
            },
            "next90-m110-media-factory-runsite-bundles": {
                "frontier_id": 5126560638,
                "milestone_id": 110,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "3accc50",
                "proof_floor_summary": "Pin M110 runsite orientation bundle proof with host clips, route-linked preview receipts, and preview-only posture",
                "owned_surfaces": [
                    "runsite_orientation_bundle",
                    "route_preview:artifact_receipts",
                ],
                "artifact_roles": [
                    "RunsiteHostClip",
                    "RunsiteRoutePreview",
                    "RunsiteAudioCompanion",
                    "RunsiteTourSibling",
                ],
                "receipt_rows": [
                    "HostClipReceiptIds",
                    "RoutePreviewReceiptIds",
                    "RoutePreviewArtifactReceipts",
                    "RunsiteRoutePreviewArtifactReceipt",
                    "AudioCompanionReceiptIds",
                    "TourSiblingReceiptIds",
                    "Artifacts",
                    "JobId",
                    "CacheTtl",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/RunsiteOrientationBundleService.cs",
                    "tests/test_m110_successor_closure_authority.py",
                    "docs/NEXT90_M110_RUNSITE_ORIENTATION_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                ],
                "extra_key": "orientation_guards",
                "extra_value": [
                    "runsite orientation bundles require at least one host clip before rendering",
                    "runsite orientation bundles require at least one route preview before rendering",
                    "preview truth posture stays pre-session-orientation-only-not-tactical-truth",
                    "route preview receipt rows preserve route segment ids plus receipt and media job identity",
                    "bundle-scoped dedupe keys include approved runsite pack, route summary, bundle id, role, route segment, category, output format, and caller dedupe",
                    "artifact receipts expose media-factory job ids for every host clip, route preview, audio companion, and optional tour sibling",
                    "orientation job dedupe and receipt hashing use length-prefixed segments so delimiter-heavy variants cannot collapse onto one media job or receipt id",
                    "runsite orientation package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                ],
            },
            "next90-m119-media-factory-starter-artifacts": {
                "frontier_id": 1413666751,
                "milestone_id": 119,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "TO_BE_FILLED_M119_COMMIT",
                "proof_floor_summary": "Pin M119 localized starter artifact closure with fallback locale bundles, support-safe note receipts, and stable mixed-case ref hashing",
                "owned_surfaces": [
                    "starter_primer_artifacts",
                    "first_session_briefing_artifacts",
                ],
                "artifact_roles": [
                    "StarterPrimerVideo",
                    "StarterPrimerAudio",
                    "StarterPrimerPreviewCard",
                    "FirstSessionBriefingVideo",
                    "FirstSessionBriefingAudio",
                    "FirstSessionBriefingPreviewCard",
                    "SupportSafeOnboardingVideo",
                    "SupportSafeOnboardingAudio",
                    "SupportSafeOnboardingPreviewCard",
                ],
                "receipt_rows": [
                    "StarterPrimerReceiptIds",
                    "FirstSessionBriefingReceiptIds",
                    "SupportSafeOnboardingReceiptIds",
                    "RequestedLocaleReceiptIds",
                    "FallbackLocaleReceiptIds",
                    "JobIds",
                    "ArtifactRefs",
                    "ReadyRefs",
                    "CaptionRefs",
                    "PreviewRefs",
                    "SupportNoteRefs",
                    "LocaleReceiptGroups",
                    "StarterArtifactLocaleReceiptGroup",
                    "BundleLocaleReceiptGroups",
                    "StarterArtifactBundleLocaleReceiptGroup",
                    "ArtifactRefReceipts",
                    "StarterArtifactArtifactRefReceipt",
                    "CaptionRefReceipts",
                    "StarterArtifactCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "StarterArtifactPreviewRefReceipt",
                    "SupportNoteReceipts",
                    "StarterArtifactSupportNoteReceipt",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/StarterArtifactBundleService.cs",
                    "tests/test_starter_artifact_rendering.py",
                    "docs/NEXT90_M119_STARTER_ARTIFACT_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                ],
                "extra_key": "starter_artifact_guards",
                "extra_value": [
                    "starter artifact rendering stays render-verified by requiring an approved starter source pack id, source pack revision id, starter lane id, and per-artifact locale plus sibling-only payloads before media jobs enqueue, and JSON payloads must match those scope fields exactly instead of passing on substring mentions alone",
                    "parseable JSON starter artifact payloads fail closed when required scope fields are missing or mismatched, so JSON strings, arrays, or wrong-sibling objects cannot bypass exact scope matching through text fallback",
                    "non-JSON starter artifact payloads require exact keyed values or delimiter-safe scope tokens, so near-match source pack ids, starter lane ids, and locales cannot pass by raw substring collision",
                    "starter artifact bundles require requested-locale and fallback locale triads for starter primer, first-session briefing, and support-safe onboarding siblings, while fallback locales stay bounded to at most two locales",
                    "starter primer and first-session video/audio siblings require caption refs, video and preview-card siblings require preview refs, and support-safe onboarding siblings require bounded support-note refs",
                    "starter artifact rendering rejects duplicate artifact refs inside one starter-lane render request",
                    "bundle-scoped dedupe keys include approved starter source pack id, source pack revision id, starter lane id, bundle kind, role, locale, category, output format, artifact ref, and caller dedupe key",
                    "receipt hashes include caption, preview, and support-note refs so starter receipts stay tied to emitted companion evidence",
                    "receipt hashes use length-prefixed locale, output-format, caption, preview, and support-note segments so delimiter-heavy starter variants cannot collapse distinct outputs onto one receipt id",
                    "normalized sibling ordering keeps receipt ids, ready refs, locale receipt groups, bundle-locale receipt groups, and aggregate ref receipts stable when callers reorder the same starter siblings",
                    "case-insensitive caption, preview, and support-note dedupe selects one canonical ref spelling before receipt hashing and aggregate ref emission so mixed-case duplicate refs stay stable when callers reorder them",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "starter artifact package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "generated and published proof artifacts require exactly one M119 successor package entry before drift comparison",
                    "generated proof requires unique M119 proof citations and unique starter artifact guard rows before drift comparison so closed-package evidence cannot silently duplicate itself while still matching canonical mirrors",
                    "queue and registry mirrors must match the canonical M119 package and task blocks exactly so repo-local proof cannot drift on status or scoped fields",
                    "proof citations stay anchored to repo-local src, tests, docs, and scripts paths so closed-package evidence cannot drift into sibling surfaces",
                    "canonical successor queue rows are now complete with `landed_commit: TO_BE_FILLED_M119_COMMIT`, so future slices can close this package only from the landed proof floor.",
                ],
            },
            "next90-m109-media-factory-build-explain-bundles": {
                "title": "Render build explainer video, audio, preview-card, and packet siblings from approved explain packets",
                "task": "Render approved Build Lab explain packets into video, audio, preview-card, and packet companions without mutating engine truth.",
                "work_task_id": "109.3",
                "frontier_id": 4037265286,
                "milestone_id": 109,
                "wave": "W9",
                "repo": "chummer6-media-factory",
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "7d5a0167",
                "proof_floor_summary": "Track M109 build explain companion bundle implementation with approved explain packets, stable sibling ordering, and first-class companion receipt refs",
                "allowed_paths": [
                    "src",
                    "tests",
                    "docs",
                    "scripts",
                ],
                "owned_surfaces": [
                    "build_explain_companion_rendering",
                    "explain_artifact_receipts",
                ],
                "artifact_roles": [
                    "BuildExplainCompanionVideo",
                    "BuildExplainCompanionAudio",
                    "BuildExplainCompanionPreviewCard",
                    "BuildExplainCompanionPacketCompanion",
                ],
                "receipt_rows": [
                    "VideoReceiptIds",
                    "AudioReceiptIds",
                    "PreviewCardReceiptIds",
                    "PacketCompanionReceiptIds",
                    "JobIds",
                    "CompanionRefs",
                    "CompanionReadyRefs",
                    "BuildExplainCompanionReadyRef",
                    "RoleReceiptGroups",
                    "BuildExplainCompanionRoleReceiptGroup",
                    "CompanionRefReceipts",
                    "BuildExplainCompanionRefReceipt",
                    "CaptionRefReceipts",
                    "BuildExplainCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "BuildExplainPreviewRefReceipt",
                    "ArtifactReceipts",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/BuildExplainCompanionRenderingService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "src/Chummer.Media.Contracts/README.md",
                    "tests/BuildExplainCompanionSmoke/Program.cs",
                    "tests/test_build_explain_companion_rendering.py",
                    "tests/test_m109_successor_package_authority.py",
                    "tests/test_m109_build_explain_proof.py",
                    "docs/NEXT90_M109_BUILD_EXPLAIN_COMPANION_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify.sh",
                    "scripts/ai/verify_m109_build_explain_companion.sh",
                ],
                "extra_key": "build_explain_guards",
                "extra_value": [
                    "request-level rendering id, approved explain packet id, explain packet revision id, and source normalize surrounding whitespace before scope enforcement, dedupe, and receipt emission so valid padded retries keep stable job ids and receipt ids",
                    "null artifact lists and null sibling entries fail closed with explicit request-scoped validation before approved explain packet normalization continues",
                    "sibling payloads must stay scoped to the approved explain packet id and explain packet revision id before media jobs enqueue, and JSON payloads must match those scope fields exactly instead of passing on substring mentions alone",
                    "JSON and keyed text scope values trim surrounding whitespace before exact scope matching so padded approved explain payloads stay valid without reopening substring spoof paths",
                    "valid JSON payloads fail closed when required scope fields are missing so object, array, or string note payloads cannot bypass approved explain packet validation through substring fallback",
                    "non-JSON scope fallback requires exact keyed values or delimited scope tokens so near-match packet and revision ids cannot slip through by substring collision",
                    "case-insensitive duplicate caption and preview refs canonicalize to one stable spelling before grouped receipt rows emit so mixed-case ref variants cannot rewrite aggregate receipt casing when callers reorder the same approved explain packet siblings",
                    "caption and preview refs trim surrounding whitespace before grouped receipt rows and receipt hashes emit so padded sibling refs cannot fork stable companion receipt ids or ready refs",
                    "build explain companion rendering requires one video, one audio, one preview-card, and one packet companion before the bundle can render",
                    "build explain video and audio siblings require caption refs while video, preview-card, and packet companions require preview refs",
                    "companion refs trim surrounding whitespace and stay unique case-insensitively per approved explain packet so downstream shelves cannot confuse sibling outputs with padded or mixed-case retries",
                    "bundle-scoped dedupe keys include approved explain packet id, explain packet revision id, rendering id, sibling role, category, output format, companion ref, and caller dedupe key",
                    "receipt hashes include caption and preview refs so companion receipts stay tied to their emitted explain siblings",
                    "receipt hashes use length-prefixed caption and preview ref segments so delimiter-heavy refs cannot collapse distinct companion outputs onto one receipt id",
                    "normalized sibling ordering keeps receipt ids, companion refs, ready refs, and grouped role, caption, and preview receipt rows stable when callers reorder the same approved explain packet artifacts",
                    "source and requested timestamp metadata stay outside bundle-scoped dedupe and receipt identity so replayed approved explain packet renders cannot fork stable job ids, receipt ids, ready refs, or grouped role receipts",
                    "companion ready refs preserve per-artifact ref, receipt id, job id, job state, output format, caption refs, preview refs, asset id, asset url, cache ttl, approval state, retention state, and storage class",
                    "role, caption, and preview receipt groups preserve aggregate job ids, grouped companion refs, and grouped artifact rows so downstream shelves do not need to reconstruct explain evidence from raw artifact receipts",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "build explain package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "canonical successor queue rows are now complete with `landed_commit: 7d5a0167`, so future slices can close this package only from the landed proof floor.",
                    "generated and published proof artifacts require exactly one M109 successor package entry before drift comparison",
                    "repo-local proof materialization now fails closed when either generated or published proof artifact repeats any successor package id, so package-specific drift checks cannot be masked by duplicate package rows elsewhere in the same proof file",
                    "queue and registry mirrors must match the canonical M109 package and task blocks exactly so repo-local proof cannot drift on status or scoped fields",
                    "proof citations stay anchored to repo-local src, tests, docs, and scripts paths so closed-package evidence cannot drift into sibling surfaces",
                ],
            },
            "next90-m145-media-factory-explain-presenter-siblings": {
                "title": "Render optional audio or presenter siblings from approved explanation packets without becoming calculation authority.",
                "task": "Render optional audio or presenter siblings from approved explanation packets while preserving packet identity, grounding scope, and first-party text fallback.",
                "work_task_id": "145.5",
                "frontier_id": 2090633046,
                "milestone_id": 145,
                "wave": "W28",
                "repo": "chummer6-media-factory",
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "7d5a0167",
                "proof_floor_summary": "Track M145 explain presenter sibling rendering with approved explanation-packet scope, stable optional sibling ordering, and first-party text fallback receipts",
                "allowed_paths": [
                    "src",
                    "tests",
                    "docs",
                    "scripts",
                ],
                "owned_surfaces": [
                    "explain_presenter_siblings:media_factory",
                    "explain_audio_video:media_factory",
                ],
                "artifact_roles": [
                    "ExplainPresenterSiblingAudio",
                    "ExplainPresenterSiblingPresenterVideo",
                ],
                "receipt_rows": [
                    "AudioReceiptIds",
                    "PresenterReceiptIds",
                    "TextFallbackReceipt",
                    "ExplainPresenterTextFallbackReceipt",
                    "JobIds",
                    "CompanionRefs",
                    "CompanionReadyRefs",
                    "ExplainPresenterSiblingReadyRef",
                    "RoleReceiptGroups",
                    "ExplainPresenterSiblingRoleReceiptGroup",
                    "CompanionRefReceipts",
                    "ExplainPresenterCompanionRefReceipt",
                    "CaptionRefReceipts",
                    "ExplainPresenterCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "ExplainPresenterPreviewRefReceipt",
                    "ArtifactReceipts",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/ExplainPresenterSiblingRenderingService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "src/Chummer.Media.Contracts/README.md",
                    "tests/ExplainPresenterSiblingSmoke/Program.cs",
                    "tests/test_explain_presenter_sibling_rendering.py",
                    "tests/test_m145_successor_package_authority.py",
                    "tests/test_m145_explain_presenter_proof.py",
                    "docs/NEXT90_M145_EXPLAIN_PRESENTER_SIBLINGS_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify.sh",
                    "scripts/ai/verify_m145_explain_presenter_siblings.sh",
                ],
                "extra_key": "explain_presenter_guards",
                "extra_value": [
                    "request-level rendering id, approved explanation packet id, explanation packet revision id, grounding scope ref, source, and first-party text fallback normalize surrounding whitespace before scope enforcement, dedupe, and receipt emission so valid padded retries keep stable job ids, receipt ids, and text fallback receipts",
                    "null artifact lists and null sibling entries fail closed with explicit request-scoped validation before approved explanation packet normalization continues",
                    "explain presenter payloads must stay scoped to the approved explanation packet id, explanation packet revision id, and grounding scope ref before media jobs enqueue, and JSON payloads must match those scope fields exactly instead of passing on substring mentions alone",
                    "parseable JSON payloads fail closed when required packet-identity or grounding-scope fields are missing or the root payload is not an object, so JSON strings, arrays, or note-only objects cannot bypass exact scope matching through text fallback",
                    "JSON and keyed text explain presenter scope values trim surrounding whitespace before exact scope matching so padded approved explanation payloads stay valid without reopening substring spoof paths",
                    "non-JSON scope fallback requires exact keyed values or delimited scope tokens so near-match packet, revision, or grounding-scope ids cannot slip through by substring collision",
                    "explain presenter audio and presenter siblings require caption refs while presenter-video siblings require preview refs",
                    "case-insensitive duplicate caption and preview refs canonicalize to one stable spelling before grouped receipt rows emit so mixed-case ref variants cannot rewrite aggregate receipt casing when callers reorder the same approved explanation packet siblings",
                    "companion refs are unique per approved explanation packet so downstream shelves cannot confuse optional audio and presenter outputs",
                    "bundle-scoped dedupe keys include approved explanation packet id, explanation packet revision id, grounding scope ref, rendering id, sibling role, category, output format, companion ref, and caller dedupe key",
                    "receipt hashes include caption refs, preview refs, and first-party text fallback so sibling receipts stay tied to their emitted explanation packet fallback posture",
                    "receipt hashes use length-prefixed caption, preview, and text-fallback segments so delimiter-heavy values cannot collapse distinct presenter outputs onto one receipt id",
                    "normalized sibling ordering keeps receipt ids, companion refs, ready refs, grouped role, caption, and preview receipt rows, and text fallback receipts stable when callers reorder the same approved explanation packet artifacts",
                    "source and requested timestamp metadata stay outside bundle-scoped dedupe and receipt identity so replayed approved explanation packet renders cannot fork stable job ids, receipt ids, ready refs, grouped role receipts, or text fallback receipts",
                    "companion ready refs preserve per-artifact ref, receipt id, job id, job state, output format, caption refs, preview refs, asset id, asset url, cache ttl, approval state, retention state, and storage class",
                    "first-party text fallback stays first-class in the render receipt and text fallback receipt so optional media surfaces never become the only explain surface",
                    "role, caption, and preview receipt groups preserve aggregate job ids, grouped companion refs, and grouped artifact rows so downstream shelves do not need to reconstruct explain presenter evidence from raw artifact receipts",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "explain presenter package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "canonical successor queue rows are now complete with `landed_commit: 7d5a0167`, so future slices can close this package only from the landed proof floor.",
                    "queue and registry mirrors must match the canonical M145 package and task blocks exactly so repo-local proof cannot drift on status or scoped fields",
                ],
            },
            "next90-m111-media-factory-concierge-bundles": {
                "frontier_id": 4132724850,
                "milestone_id": 111,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "7d5a0167",
                "proof_floor_summary": "Track M111 install-aware concierge bundle implementation with exact package identity, scoped install-aware payloads, stable sibling ordering, and bounded sibling notes",
                "owned_surfaces": [
                    "release_explainer_artifacts",
                    "support_closure_artifacts",
                    "public_concierge_companions",
                ],
                "artifact_roles": [
                    "InstallAwareReleaseExplainerVideo",
                    "InstallAwareReleaseExplainerAudio",
                    "InstallAwareReleaseExplainerPreviewCard",
                    "InstallAwareSupportClosureVideo",
                    "InstallAwareSupportClosureAudio",
                    "InstallAwareSupportClosurePreviewCard",
                    "InstallAwarePublicConciergeVideo",
                    "InstallAwarePublicConciergeAudio",
                    "InstallAwarePublicConciergePreviewCard",
                ],
                "receipt_rows": [
                    "ReleaseExplainerReceiptIds",
                    "SupportClosureReceiptIds",
                    "PublicConciergeReceiptIds",
                    "JobIds",
                    "CompanionRefs",
                    "CompanionReadyRefs",
                    "InstallAwareConciergeCompanionReadyRef",
                    "CaptionRefs",
                    "PreviewRefs",
                    "SiblingNoteRefs",
                    "BundleReceiptGroups",
                    "InstallAwareConciergeBundleReceiptGroup",
                    "RoleReceiptGroups",
                    "InstallAwareConciergeRoleReceiptGroup",
                    "CompanionRefReceipts",
                    "InstallAwareConciergeCompanionRefReceipt",
                    "CaptionRefReceipts",
                    "InstallAwareConciergeCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "InstallAwareConciergePreviewRefReceipt",
                    "SiblingNoteReceipts",
                    "InstallAwareConciergeSiblingNoteReceipt",
                    "ArtifactReceipts",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/InstallAwareConciergeBundleService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "tests/InstallAwareConciergeSmoke/Program.cs",
                    "tests/test_install_aware_concierge_rendering.py",
                    "tests/test_m111_successor_package_authority.py",
                    "tests/test_m111_install_aware_concierge_proof.py",
                    "docs/NEXT90_M111_INSTALL_AWARE_CONCIERGE_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify_m111_install_aware_concierge.sh",
                    "scripts/ai/verify.sh",
                ],
                "extra_key": "install_aware_concierge_guards",
                "extra_value": [
                    "install-aware concierge payloads must stay scoped to the install-aware packet id, installed build receipt id, and artifact identity id before media jobs enqueue, JSON payloads must match those scope fields exactly, and non-JSON payloads must satisfy keyed or delimiter-safe scope matching instead of raw substring mentions alone",
                    "request-level rendering id, install-aware packet id, installed build receipt id, artifact identity id, and source values normalize surrounding whitespace before scope enforcement so valid concierge requests do not fail on padded caller input",
                    "parseable JSON payloads fail closed when required scope fields are missing or the root payload is not an object, so JSON strings, arrays, or note-only objects cannot bypass exact install-aware scope matching through text fallback",
                    "JSON and keyed text scope values trim surrounding whitespace before exact scope matching so padded install-aware payloads stay valid without reopening substring spoof paths",
                    "install-aware concierge bundles require release explainer, support closure, and public concierge siblings to each emit video, audio, and preview-card artifacts before the bundle can render",
                    "install-aware concierge video and audio companions require caption refs while video and preview-card companions require preview refs",
                    "install-aware concierge artifacts require at least one sibling note ref and keep sibling notes bounded to at most two refs per artifact",
                    "companion refs are unique per install-aware packet so downstream shelves cannot confuse release, support, and public concierge outputs",
                    "bundle-scoped dedupe keys include install-aware packet id, installed build receipt id, artifact identity id, rendering id, bundle kind, sibling role, category, output format, companion ref, and caller dedupe key",
                    "source and requested timestamp metadata stay outside bundle-scoped dedupe, receipt identity, and companion-ready identity so replayed install-aware packets cannot fork stable jobs, receipt ids, or ready refs",
                    "normalized artifact ordering plus normalized caption, preview, and sibling-note ref ordering keep receipt ids, companion refs, ready refs, and grouped bundle, role, caption, preview, and sibling-note receipt rows stable when callers reorder the same install-aware packet artifacts",
                    "case-insensitive caption, preview, and sibling-note dedupe selects one canonical ref spelling before receipt hashing and aggregate ref emission so mixed-case duplicate refs stay stable when callers reorder them",
                    "receipt hashes include caption, preview, and sibling-note refs so concierge receipts stay tied to their emitted release, support, and public siblings",
                    "receipt hashes use length-prefixed caption, preview, and sibling-note ref segments so delimiter-heavy refs cannot collapse distinct concierge outputs onto one receipt id",
                    "top-level caption, preview, and sibling-note aggregate refs stay first-class receipt rows so downstream shelves can surface bundle-wide concierge evidence without reconstructing it from grouped rows",
                    "companion ready refs preserve per-artifact ref, receipt id, job id, job state, output format, caption refs, preview refs, sibling note refs, asset id, asset url, cache ttl, approval state, retention state, and storage class",
                    "caption, preview, and sibling-note grouped receipt rows preserve bundle kinds, roles, and grouped asset urls so downstream shelves can publish first-class concierge evidence without reconstructing it from raw artifact receipts",
                    "bundle, role, caption, preview, and sibling-note receipt groups preserve aggregate job ids, grouped companion refs, grouped bundle kinds or roles, and grouped artifact rows so downstream shelves do not need to reconstruct concierge evidence from raw artifact receipts",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "install-aware concierge package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "canonical successor queue rows are now complete with `landed_commit: 7d5a0167`, so future slices can close this package only from the landed proof floor.",
                ],
            },
            "next90-m115-media-factory-exchange-previews": {
                "frontier_id": 1547375325,
                "milestone_id": 115,
                "status": "in_progress",
                "completion_action": "implementation_only",
                "proof_floor_commit": "unlanded",
                "proof_floor_summary": "Track M115 recap, replay, and exchange preview rendering with inspectable siblings, stable grouped receipts, and replay-safe dedupe",
                "owned_surfaces": [
                    "recap_preview_artifacts",
                    "replay_exchange_preview_artifacts",
                ],
                "artifact_roles": [
                    "RecapPreviewCard",
                    "RecapInspectableSibling",
                    "ReplayPreviewCard",
                    "ReplayInspectableSibling",
                    "ExchangePreviewCard",
                    "ExchangeInspectableSibling",
                ],
                "receipt_rows": [
                    "Artifacts",
                    "BundleReceipts",
                    "ReplayExchangePreviewBundleReceipt",
                    "KindReceiptGroups",
                    "ReplayExchangePreviewKindReceiptGroup",
                    "PreviewCardReceiptIds",
                    "InspectableSiblingReceiptIds",
                    "BundleRefs",
                    "LineageRefs",
                    "CompatibilityReceiptIds",
                    "ProvenanceReceiptIds",
                    "BoundedLossReceiptIds",
                    "JobIds",
                    "ReadyRefs",
                    "ReplayExchangePreviewReadyRef",
                    "ArtifactRefReceipts",
                    "ReplayExchangePreviewArtifactRefReceipt",
                    "CaptionRefReceipts",
                    "ReplayExchangePreviewCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "ReplayExchangePreviewPreviewRefReceipt",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/ReplayExchangePreviewRenderingService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "tests/ReplayExchangePreviewSmoke/Program.cs",
                    "tests/test_replay_exchange_preview_rendering.py",
                    "tests/test_m115_replay_exchange_preview_proof.py",
                    "tests/test_m115_successor_package_authority.py",
                    "docs/NEXT90_M115_REPLAY_EXCHANGE_PREVIEW_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify_m115_replay_exchange_previews.sh",
                    "scripts/ai/verify.sh",
                ],
                "extra_key": "exchange_preview_guards",
                "extra_value": [
                    "replay, recap, and exchange bundles must each stay first-class so portable artifact shelves can inspect every preview lane directly",
                    "every bundle preserves BundleRef, LineageRef, CompatibilityReceiptId, ProvenanceReceiptId, and BoundedLossReceiptId in both artifact receipts and grouped receipts",
                    "preview-card and inspectable sibling artifacts must both preserve preview refs so downstream shelves can render bounded previews without re-querying artifact internals",
                    "bundle refs and artifact refs stay unique per render request so recap, replay, and exchange outputs cannot cross-link accidentally",
                    "bundle-scoped dedupe keys include bundle kind, bundle ref, lineage ref, compatibility receipt id, provenance receipt id, bounded-loss receipt id, role, category, output format, artifact ref, and caller dedupe key",
                    "source and requested timestamp metadata stay outside bundle-scoped dedupe and receipt identity so replayed preview renders cannot fork stable jobs, receipt ids, or ready refs",
                    "normalized bundle ordering plus normalized caption and preview ref ordering keep preview-card receipt ids, inspectable sibling receipt ids, ready refs, and grouped kind, caption, and preview receipt rows stable when callers reorder the same bundles",
                    "case-insensitive caption and preview dedupe selects one canonical ref spelling before receipt hashing and aggregate ref emission so mixed-case duplicate refs stay stable when callers reorder them",
                    "receipt hashes include caption and preview refs so replay, recap, and exchange sibling receipts stay tied to their emitted bounded preview posture",
                    "receipt hashes use length-prefixed caption and preview ref segments so delimiter-heavy variants cannot collapse distinct outputs onto one receipt id",
                    "kind, caption, and preview grouped receipt rows preserve aggregate job ids, grouped artifact refs, and grouped artifact rows so downstream shelves do not need to reconstruct recap, replay, and exchange evidence from raw artifact receipts",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite render time with a newer request timestamp",
                    "replay/exchange preview package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                ],
            },
            "next90-m116-media-factory-creator-promo-kits": {
                "frontier_id": 4956678153,
                "milestone_id": 116,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "29ea571",
                "proof_floor_summary": "Pin M116 creator promo kit closure with approved manifest scope, stable sibling ordering, and first-class preview and caption receipt groups",
                "owned_surfaces": [
                    "creator_promo_kits",
                    "publication_preview_artifacts",
                ],
                "artifact_roles": [
                    "CreatorPromoVideo",
                    "CreatorPromoPoster",
                    "CreatorPromoPreviewCard",
                ],
                "receipt_rows": [
                    "PromoVideoReceiptIds",
                    "PromoPosterReceiptIds",
                    "PreviewCardReceiptIds",
                    "JobIds",
                    "ArtifactRefs",
                    "ReadyRefs",
                    "CreatorPromoKitReadyRef",
                    "CaptionRefs",
                    "PreviewRefs",
                    "RoleReceiptGroups",
                    "CreatorPromoKitRoleReceiptGroup",
                    "ArtifactRefReceipts",
                    "CreatorPromoKitArtifactRefReceipt",
                    "CaptionRefReceipts",
                    "CreatorPromoCaptionRefReceipt",
                    "PreviewRefReceipts",
                    "CreatorPromoPreviewRefReceipt",
                    "ArtifactReceipts",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/CreatorPromoKitRenderingService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "tests/CreatorPromoKitSmoke/Program.cs",
                    "tests/test_creator_promo_kit_rendering.py",
                    "tests/test_m116_creator_promo_proof.py",
                    "tests/test_m116_successor_package_authority.py",
                    "docs/NEXT90_M116_CREATOR_PROMO_KIT_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify_m116_creator_promo_kits.sh",
                ],
                "extra_key": "creator_promo_guards",
                "extra_value": [
                    "creator promo kit rendering stays render-verified by requiring an approved manifest id and manifest revision id plus sibling-only payloads before media jobs enqueue, and JSON payloads must match those scope fields exactly instead of passing on substring mentions alone",
                    "parseable JSON creator promo payloads fail closed when required scope fields are missing or mismatched, so JSON strings, arrays, or wrong-sibling objects cannot bypass exact scope matching through text fallback",
                    "non-JSON creator promo payloads require exact keyed values or delimiter-safe scope tokens, so near-match approved manifest ids and manifest revision ids cannot pass by raw substring collision",
                    "creator promo kit rendering requires one promo video, one promo poster, and one preview-card sibling before the bundle can render",
                    "creator promo video siblings require caption refs while every creator promo sibling requires at least one preview ref",
                    "creator promo rendering rejects duplicate artifact refs inside one approved manifest render request",
                    "bundle-scoped dedupe keys include approved manifest id, manifest revision id, rendering id, sibling role, category, output format, artifact ref, and caller dedupe key",
                    "receipt hashes include caption and preview refs so creator promo receipts stay tied to emitted preview and caption siblings",
                    "receipt hashes use length-prefixed caption and preview ref segments so delimiter-heavy creator promo refs cannot collapse distinct outputs onto one receipt id",
                    "normalized sibling ordering keeps receipt ids, artifact refs, ready refs, and grouped role, caption, and preview receipt rows stable when callers reorder the same approved manifest siblings",
                    "case-insensitive caption and preview dedupe selects one canonical ref spelling before receipt hashing and aggregate ref emission so mixed-case duplicate refs stay stable when callers reorder them",
                    "source and requested timestamp metadata stay outside bundle-scoped dedupe and receipt identity so replayed approved manifest renders cannot fork stable job ids, receipt ids, ready refs, or grouped role receipts",
                    "creator promo ready refs preserve per-artifact ref, receipt id, job id, job state, output format, caption refs, preview refs, asset id, asset url, cache ttl, approval state, retention state, and storage class",
                    "role, caption, and preview receipt groups preserve aggregate job ids, grouped artifact refs, and grouped artifact rows so downstream shelves do not need to reconstruct creator promo evidence from raw artifact receipts",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "creator promo package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                ],
            },
            "next90-m113-media-factory-gm-prep-packets": {
                "title": "Render opposition and GM prep packets from governed source packs",
                "task": "Produce packet, preview, and optional briefing artifacts for opposition, scenes, and prep-library entries.",
                "work_task_id": "113.4",
                "frontier_id": 3813748639,
                "milestone_id": 113,
                "wave": "W11",
                "repo": "chummer6-media-factory",
                "status": "complete",
                "landed_commit": "7d5a0167",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "7d5a0167",
                "proof_floor_summary": "Pin M113 governed GM prep packet closure with opposition-required entries, optional briefing siblings, and first-class subject receipt groups",
                "allowed_paths": [
                    "src",
                    "tests",
                    "docs",
                    "scripts",
                ],
                "owned_surfaces": [
                    "gm_prep_packets",
                    "opposition_packet_artifacts",
                ],
                "artifact_roles": [
                    "GmPrepOppositionPacket",
                    "GmPrepOppositionPreview",
                    "GmPrepOppositionBriefing",
                    "GmPrepScenePacket",
                    "GmPrepScenePreview",
                    "GmPrepSceneBriefing",
                    "GmPrepLibraryPacket",
                    "GmPrepLibraryPreview",
                    "GmPrepLibraryBriefing",
                ],
                "receipt_rows": [
                    "EntryReceipts",
                    "GmPrepPacketEntryReceipt",
                    "SubjectReceiptGroups",
                    "GmPrepPacketSubjectReceiptGroup",
                    "PacketReceiptIds",
                    "PreviewReceiptIds",
                    "BriefingReceiptIds",
                    "OppositionPacketReceiptIds",
                    "ScenePacketReceiptIds",
                    "PrepLibraryPacketReceiptIds",
                    "PacketRefs",
                    "JobIds",
                    "ArtifactReceipts",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "proof": [
                    "src/Chummer.Media.Factory.Runtime/Assets/GmPrepPacketBundleService.cs",
                    "src/Chummer.Media.Contracts/Compatibility/RunServices/MediaFactoryContracts.cs",
                    "tests/GmPrepPacketSmoke/Program.cs",
                    "tests/test_gm_prep_packet_rendering.py",
                    "tests/test_m113_gm_prep_packet_proof.py",
                    "tests/test_m113_successor_package_authority.py",
                    "docs/NEXT90_M113_GM_PREP_PACKET_PROOF_FLOOR.md",
                    "scripts/ai/materialize_media_release_proof.py",
                    "scripts/ai/verify_m113_gm_prep_packets.sh",
                    "scripts/ai/verify.sh",
                ],
                "extra_key": "gm_prep_packet_guards",
                "extra_value": [
                    "GM prep packet rendering stays render-verified by requiring a governed source pack id, source pack revision id, packet ref, and source entry id plus sibling-only payloads before media jobs enqueue, and JSON payloads must match those scope fields exactly instead of passing on substring mentions alone",
                    "parseable JSON GM prep payloads fail closed when required scope fields are missing or mismatched, so JSON strings, arrays, or wrong-sibling objects cannot bypass exact scope matching through text fallback",
                    "non-JSON GM prep payloads require exact keyed values or delimiter-safe scope tokens, so near-match source pack ids, packet refs, and source entry ids cannot pass by raw substring collision",
                    "JSON and keyed text GM prep scope values trim surrounding whitespace before exact scope matching so padded governed payloads stay valid without reopening substring spoof paths",
                    "GM prep packet rendering fails closed when the request contains null entries or a governed entry drops its required packet or preview artifact before normalization continues",
                    "GM prep packet rendering requires at least one opposition entry and keeps scene and prep-library entries optional within the same governed render request",
                    "GM prep packet entries require packet and preview artifacts while briefing artifacts stay optional per governed entry",
                    "GM prep packet rendering rejects duplicate source entries and duplicate packet refs inside one governed render request",
                    "bundle-scoped dedupe keys include governed source pack id, source pack revision id, rendering id, subject kind, source entry id, packet ref, artifact role, category, output format, and caller dedupe key",
                    "receipt hashes use length-prefixed subject-kind, artifact-role, and output-format segments so delimiter-heavy GM prep variants cannot collapse distinct outputs onto one receipt id",
                    "entry receipt ids and subject receipt group ids stay scoped to governed source pack id, source pack revision id, and rendering id so reused packet refs cannot alias grouped evidence across governed packs",
                    "subject receipt groups preserve grouped entry ids, packet refs, packet receipt ids, preview receipt ids, optional briefing receipt ids, aggregate job ids, and grouped artifact rows so downstream shelves do not need to reconstruct governed prep evidence from raw artifact receipts",
                    "GM prep packet artifact receipts preserve asset urls, approval state, retention state, and storage class alongside packet, preview, and optional briefing outputs",
                    "rendered timestamps resolve from completed media jobs so later deduped retries cannot rewrite bundle render time with a newer request timestamp",
                    "GM prep packet package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "generated and published proof artifacts require exactly one M113 successor package entry before drift comparison",
                    "generated proof requires unique M113 proof citations and unique GM prep guard rows before drift comparison so closed-package evidence cannot silently duplicate itself while still matching canonical mirrors",
                    "generated proof requires unique M113 artifact roles and unique receipt rows before drift comparison so closed-package evidence cannot silently duplicate rendered sibling claims or receipt surfaces while still matching canonical mirrors",
                    "generated proof requires the exact pinned M113 proof citations, artifact roles, and receipt rows before drift comparison so closed-package evidence cannot quietly add sibling surfaces while still matching canonical mirrors",
                    "generated and published proof artifacts now pin the exact M113 GM prep guard rows directly on the successor package entry, so repo-local closure proof cannot silently rewrite the closed-package scope rules while still matching on identity alone",
                    "queue and registry mirrors must match the canonical M113 package and task blocks exactly so repo-local proof cannot drift on status or scoped fields",
                    "proof citations stay anchored to repo-local src, tests, docs, and scripts paths so closed-package evidence cannot drift into sibling surfaces",
                    "every pinned M113 proof citation must resolve to a repo-local file before generated or published closure proof can stay green, so closed-package evidence cannot cite deleted surfaces while still matching on strings alone",
                    "generated and published proof artifacts now pin `landed_commit: 7d5a0167` directly on the M113 successor package entry, so repo-local closure proof cannot drift behind the canonical queue receipt while still reporting `status: complete`.",
                    "canonical successor queue rows are now complete with `landed_commit: 7d5a0167`, so future slices can close this package only from the landed proof floor.",
                ],
            },
            "next90-m135-media-factory-close-media-contracts-render-jobs-previews-manifests-arc": {
                "frontier_id": 4720040715,
                "milestone_id": 135,
                "status": "complete",
                "completion_action": "verify_closed_package_only",
                "proof_floor_commit": "unlanded",
                "proof_floor_summary": "Close the repo-wide media coverage bundle by pinning contracts, render jobs, previews, manifests, provider adapters, archive posture, and asset lifecycle evidence to one verify-only package entry",
                "allowed_paths": [
                    "src",
                    "tests",
                    "docs",
                    "scripts",
                ],
                "owned_surfaces": [
                    "close_media_contracts_render_jobs:media_factory",
                ],
                "artifact_roles": [
                    "DocumentPdf",
                    "DocumentThumbnailImage",
                    "PortraitImageVariant",
                    "NarrativeBriefVideo",
                    "RouteCinemaResult",
                    "StructuredRecipePacketBundle",
                    "CampaignColdOpen",
                    "BuildExplainCompanionPacketCompanion",
                    "ExplainPresenterSiblingPresenterVideo",
                    "InstallAwarePublicConciergePreviewCard",
                    "ReplayPreviewCard",
                    "GmPrepOppositionPacket",
                    "CreatorPromoKitVideo",
                    "StarterPrimerVideo",
                ],
                "receipt_rows": [
                    "PublicationReadyRefs",
                    "CaptionRefReceipts",
                    "PreviewRefReceipts",
                    "ArtifactReceipts",
                    "RoleReceiptGroups",
                    "JobIds",
                    "AssetUrl",
                    "ApprovalState",
                    "RetentionState",
                    "StorageClass",
                ],
                "extra_key": "media_coverage_guards",
                "extra_value": [
                    "media coverage closure keeps the contracts assembly marker, render kind inventory, render-job lifecycle, preview receipts, manifest publication proof, provider-adapter posture, and archive retention state pinned to repo-local render ownership only",
                    "closure coverage package composes the render-verified successor proof floors for structured recipes, campaign briefings, build explain, runsite orientation, install-aware concierge, GM prep packets, replay or exchange previews, creator promo kits, starter artifacts, and explain presenter siblings without reopening runtime ownership boundaries",
                    "published release proof and artifact publication certification must match the freshly materialized M135 package entry exactly so repo-local closure cannot drift behind stale published snapshots",
                    "media coverage package authority requires exactly one canonical queue row per mirror and exactly one registry task block",
                    "proof citations stay anchored to repo-local src, tests, docs, and scripts paths so closed-package evidence cannot drift into sibling surfaces",
                ],
            },
        }

        for payload in (release, certification):
            packages = payload["successor_packages"]
            self.assertEqual(set(expected_packages), {package["package_id"] for package in packages})
            self.assertEqual(len(expected_packages), len(packages))

            for package in packages:
                expected = expected_packages[package["package_id"]]
                self.assertEqual(expected["frontier_id"], package["frontier_id"])
                self.assertEqual(expected["milestone_id"], package["milestone_id"])
                self.assertEqual(expected["status"], package["status"])
                if "landed_commit" in expected:
                    self.assertEqual(expected["landed_commit"], package["landed_commit"])
                self.assertEqual(expected["completion_action"], package["completion_action"])
                self.assertEqual(expected["proof_floor_commit"], package["proof_floor_commit"])
                self.assertEqual(expected["proof_floor_summary"], package["proof_floor_summary"])
                if "allowed_paths" in expected:
                    self.assertEqual(expected["allowed_paths"], package["allowed_paths"])
                self.assertEqual(expected["owned_surfaces"], package["owned_surfaces"])
                self.assertEqual(expected["artifact_roles"], package["artifact_roles"])
                self.assertEqual(expected["receipt_rows"], package["receipt_rows"])
                if package["package_id"] == "next90-m113-media-factory-gm-prep-packets":
                    self.assertEqual(expected["proof"], package["proof"])
                self.assertEqual(expected["extra_value"], package[expected["extra_key"]])
                self.assertEqual(len(package["proof"]), len(set(package["proof"])))
                self.assertEqual(len(package["artifact_roles"]), len(set(package["artifact_roles"])))
                self.assertEqual(len(package["receipt_rows"]), len(set(package["receipt_rows"])))
                self.assertEqual(len(package[expected["extra_key"]]), len(set(package[expected["extra_key"]])))

        self.assertEqual(
            "render jobs, manifests, previews, campaign briefing bundles, starter onboarding bundles, runsite orientation bundles, structured recipe bundles, build explain companion bundles, explain presenter sibling bundles, install-aware concierge bundles, replay/exchange preview bundles, creator promo kit bundles, GM prep packet bundles, and asset lifecycle",
            release["evidence"]["release_surface"],
        )

    def test_published_m109_package_entry_matches_fresh_materialization(self):
        published_release = json.loads(
            (ROOT / ".codex-studio/published/MEDIA_LOCAL_RELEASE_PROOF.generated.json").read_text(encoding="utf-8")
        )
        published_certification = json.loads(
            (ROOT / ".codex-studio/published/ARTIFACT_PUBLICATION_CERTIFICATION.generated.json").read_text(
                encoding="utf-8"
            )
        )

        with tempfile.TemporaryDirectory() as tmp:
            subprocess.run(
                [
                    sys.executable,
                    "scripts/ai/materialize_media_release_proof.py",
                    "--out-dir",
                    tmp,
                    "--status",
                    "passed",
                ],
                cwd=ROOT,
                check=True,
                stdout=subprocess.DEVNULL,
            )
            generated_release = json.loads((Path(tmp) / "MEDIA_LOCAL_RELEASE_PROOF.generated.json").read_text(encoding="utf-8"))
            generated_certification = json.loads(
                (Path(tmp) / "ARTIFACT_PUBLICATION_CERTIFICATION.generated.json").read_text(encoding="utf-8")
            )

        self.assertEqual(
            self.assert_single_package_entry(generated_release["successor_packages"], M109_PACKAGE_ID),
            self.assert_single_package_entry(published_release["successor_packages"], M109_PACKAGE_ID),
            "published MEDIA_LOCAL_RELEASE_PROOF.generated.json should match the current M109 package entry exactly",
        )
        self.assertEqual(
            self.assert_single_package_entry(generated_certification["successor_packages"], M109_PACKAGE_ID),
            self.assert_single_package_entry(published_certification["successor_packages"], M109_PACKAGE_ID),
            "published ARTIFACT_PUBLICATION_CERTIFICATION.generated.json should match the current M109 package entry exactly",
        )


if __name__ == "__main__":
    unittest.main()
